// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5nIBunap4inXi6QZG7vIqsN_uIBtptWk',
    appId: '1:566628140540:web:5e491c1e2b8cf1e66b1e79',
    messagingSenderId: '566628140540',
    projectId: 'testapp-e6712',
    authDomain: 'testapp-e6712.firebaseapp.com',
    storageBucket: 'testapp-e6712.firebasestorage.app',
    measurementId: 'G-X6RH1RX4GF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD87MAaimxWMit-KY3LQwi4AKFuCnNyFaI',
    appId: '1:566628140540:android:a248c8b3ecb213976b1e79',
    messagingSenderId: '566628140540',
    projectId: 'testapp-e6712',
    storageBucket: 'testapp-e6712.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPTnHju2jleXbA61rAwpUKuzDWiNJRcXg',
    appId: '1:566628140540:ios:148010682dbe7d1d6b1e79',
    messagingSenderId: '566628140540',
    projectId: 'testapp-e6712',
    storageBucket: 'testapp-e6712.firebasestorage.app',
    iosBundleId: 'com.example.testTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPTnHju2jleXbA61rAwpUKuzDWiNJRcXg',
    appId: '1:566628140540:ios:148010682dbe7d1d6b1e79',
    messagingSenderId: '566628140540',
    projectId: 'testapp-e6712',
    storageBucket: 'testapp-e6712.firebasestorage.app',
    iosBundleId: 'com.example.testTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5nIBunap4inXi6QZG7vIqsN_uIBtptWk',
    appId: '1:566628140540:web:d321cdc24a7dc2416b1e79',
    messagingSenderId: '566628140540',
    projectId: 'testapp-e6712',
    authDomain: 'testapp-e6712.firebaseapp.com',
    storageBucket: 'testapp-e6712.firebasestorage.app',
    measurementId: 'G-QTFQMNRVXK',
  );
}
